#!/usr/bin/env zsh
# Uses libvips to convert the input image to JPEG.
# First two arguments are the input and output filename.
# Optional third argument of JPEG quality level, defaults to 85.
# Happily overwrites existing output files.
if ! (( ${+commands[vips]} )); then
  echo -e "'vips' command not found, install the libvips package.\n" >&2
  return 1
fi

local input_file="${1}"
local output_file="${2}"
local quality="${3:-85}"
if [[ ! -e "${input_file}" ]]; then
  echo -e "'${input_file}' not found.\n" >&2
  return 1
fi

vips jpegsave "${input_file}" "${output_file}" \
  --Q "${quality}" --optimize-scans --optimize-coding --interlace
