#!/usr/bin/env zsh
# Most-frequently run commands, counting only the base cmd and the first argument.
# Defaults to top 20, optional arg overrides that.
[[ -z "${HISTFILE}" ]] && {{ echo -e "HISTFILE env var not configured. Aborting.\n" >&2; return 1; }

local -x LC_ALL=C
fc -A
sed -E 's/^: [0-9]+:[0-9]+;//' "${HISTFILE}" | awk 'NF {print ($2 == "" ? $1 : $1 " " $2)}' | sort | uniq -c | sort -nr | head -n "${1:-20}"
