#!/usr/bin/env zsh
# Most-frequently invoked lines of shell input.
# Defaults to top 20, optional arg overrides that.
[[ -z "${HISTFILE}" ]] && {{ echo -e "HISTFILE env var not configured. Aborting.\n" >&2; return 1; }

local -x LC_ALL=C
fc -A
sed -E 's/^: [0-9]+:[0-9]+;//' "${HISTFILE}" | sort | uniq -c | sort -nr | head -n "${1:-20}"
